### PR TITLE
Fail silently on resolving variables, falling back to settings.TEMPLATE_STRING_IF_INVALID

### PR DESCRIPTION
**Pull request by jaap3**
Currently fancy_tag raises really hard to debug VariableDoesNotExist exceptions when looking up variables that are not available in the context.

Falling back to settings.TEMPLATE_STRING_IF_INVALID is much more user friendly. This requires tag authors to check their input values, but at least VariableDoesNotExist are now recoverable (by modifying the template tags).

Added tox to run the tests on multiple Python/Django versions at once, and changed the test settings so Django 1.4 can also be tested.

Updated some text files to note the changes made in this pull request, and updated the copyright year.

Changed the version number to 0.2.0 to signify serious change in behavior. Although I don't think anybody is relying on VariableDoesNotExist being raised.

Hope you can pull this (and release it). It's been an issue that has been mystifying some of the developers over here for a long time :).

### CODE REVIEW

**Comment by jaap3** [comment]
@osirius I just noticed you are no longer part of the Trapeze organization. Are you still the owner/maintainer of this package?

**Comment by greatestape** [comment]
I'll check out the pull request and try to get a new release out for you today, but you should check out the new stuff in Django 1.4. They've folded most of fancy_tag into core, so you may not even need this anymore.

**Comment by jaap3** [comment]
Thanks!

I know about Django's new assignment_tag. I just got loads of legacy projects that are not 1.4 ready yet, and apps that are used in the previously mentioned non Django 1.4 projects. We have used fancy_tag heavily over the years, it's really good ;).

Also I believe the Django 1.4 assignment_tag only supports assignment and I like the flexibility of assignment being optional. It also makes it harder to port my existing fancy_tags to assignment tags :(.

Did you have anything to do with the assignment_tag as found in Django core? If so, congrats!

**Comment by greatestape** [comment]
I think they borrowed stuff from this. Your merge looks good, so in it goes!

**Comment by greatestape** [comment]
It's up on pypi

**Comment by jaap3** [comment]
Awesome, thanks for the swift follow up!

**Pull request merged**
